name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - id: os_lower
        uses: ASzc/change-string-case-action@v6
        with:
          string: upscayl-bin-20240601-103425-${{ runner.os }}

      - uses: robinraju/release-downloader@v1
        name: download upscayl
        with:
          repository: 'upscayl/upscayl-ncnn'
          tag: '20240601-103425'
          fileName: '${{ steps.os_lower.outputs.lowercase }}.zip'

      - name: Unpack Upscayl
        run: |
          7z x ${{ steps.os_lower.outputs.lowercase }}.zip
          move ${{ steps.os_lower.outputs.lowercase }}\upscayl-bin.exe ..
      
      - name: Build Aeternum
        run: cargo build --release --features "package"

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: assets/aeternum.iss
          options: /O+ /version=${{ github.ref_name }}
